main_settings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import LoginView, LogoutView, RegisterView


urlpatterns = [
    path('admin/', admin.site.urls),

    path("",include("pages.urls",namespace="pages")), 
    path("login/",LoginView.as_view(),name="login"),
    path("register/",RegisterView.as_view(),name="register"),
    path("logout/",LogoutView.as_view(),name="logout"),
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from .views import*
from accounts.middlewares import customer_middleware
app_name="pages"
urlpatterns = [
       path("",HomeView.as_view(),name='home'),
       path("shop/",ProductListView.as_view(),name='product-list'),
       path("cart/",CartView.as_view(),name='cart'),
       path("checkout/",customer_middleware(CheckoutView.as_view()),name='checkout'),
       path("order/",customer_middleware(OrderView.as_view()),name='order'),
       path("product/detail-of-<slug:slug>/",ProductDetailView.as_view(),name='product-detail'),
       

       path("add-to-cart/",AddToCartView.as_view(),name="add-to-cart"),
       path("category/<slug:slug>/",SubCategoryView.as_view(),name="sub_category-list"),
       path("product/detail-of-<slug:slug>/review/",ProductReviewView.as_view(),name='product-review'),


       path("search-product/<str:query>/",get__names)
      
      

]

products/models.py
import uuid
from django.utils.html import format_html
from django.db import models
from accounts.models import CustomUser
import ast 
from django.utils.text import slugify


# Create your models here.
class BaseModel(models.Model):
    slug=models.SlugField(unique=True,blank=True,null=True)
    updated=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract=True 


class Category(BaseModel):
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(unique=True,blank=True,null=True)

    def __str__(self) -> str:
        return self.name 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args,**kwargs)

class SubCategory(BaseModel):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(blank=True,null=True)

    def __str__(self) -> str:
        return self.name 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args,**kwargs)


class Product(BaseModel):
    sub_category=models.ForeignKey(SubCategory,on_delete=models.CASCADE)
    title=models.CharField(max_length=255,unique=True)
    thumbnail=models.ImageField(upload_to="media")
    price=models.PositiveBigIntegerField()
    discount_price=models.PositiveBigIntegerField(blank=True,null=True)
    description=models.TextField()
    MEN_OR_WOMEN=(("Men's","Men's"),("Women's","Women's"),("Kid's","Kid's"),("Everyone","Everyone"))
    men_or_women=models.CharField(max_length=8,choices=MEN_OR_WOMEN)
    is_active=models.BooleanField(default=True)
    sale_count=models.PositiveBigIntegerField(default=0)

    def __str__(self) -> str:
        return self.title 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        return super().save(*args,**kwargs)


    def get_all_images(self):
        images=f"<img src='{self.thumbnail.url}' height='25' width='25' style='border-radius:50%;'> - "
        img_list=ProductImage.objects.filter(product__id=self.id)
        for img in img_list:
            images+=f"<img src='{str(img.image.url)}' height='25' width='25' style='border-radius:50%;'> - "
            
        return format_html(images)

    def multiple_image(self):
        img_list=ProductImage.objects.filter(product__id=self.id)
        images=[]
        for obj in img_list:
            images.append(obj.image.url)
        return images



class ProductImage(models.Model):
    product=models.ForeignKey(Product,related_name='product',on_delete=models.CASCADE)
    image=models.ImageField(upload_to="media")

    def __str__(self):
        return self.product.title


def create_random_code():
    code="ES-"+str(uuid.uuid4()).replace("-","").upper()[:10]
    order=Order.objects.filter(unique_id=code)
    while True:
        if order.exists():
            code="ES-"+str(uuid.uuid4()).replace("-","").upper()[:12]
        else:
            break
    return code 

class Order(models.Model):
    unique_id=models.CharField(max_length=12,default=create_random_code,blank=True,null=True)
    name_and_quantity=models.TextField()
    total=models.PositiveBigIntegerField()
    status=models.CharField(max_length=10,choices=(("Pending","Pending"),("Received","Received")),default="Pending")
    paid=models.BooleanField(default=False)
    order_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    updated=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.unique_id

    def save(self,*args,**kwargs):
        if self.status=="Received":
            self.paid=True 
        return super().save(*args,**kwargs)

    def product_list(self):
        text=ast.literal_eval(self.name_and_quantity)
        data=""
        for i in text:
           obj=Product.objects.get(id=i["id"])
           data+=f"<img src='{obj.thumbnail.url}' style='height:25px;weight:25px;border-radius:50%;'> {Product.objects.get(id=i['id']).title}( {i['quantity']} )<br>"
        return format_html(data)

    
    def customer_details(self):
        address=Address.objects.filter(order__id=self.id).last()
        detail=""
        detail+=f'<p>Name : {address.full_name}</p>'
        detail+=f'<p>Phone : {address.mobile}</p>'
        detail+=f'<p>Email : {address.email}</p>'
        detail+=f'<p>Address : {address.address},{address.city},{address.country}</p>'
        return format_html(detail)




class Address(models.Model):
    full_name=models.CharField(max_length=255)
    email=models.EmailField()
    mobile=models.CharField(max_length=255)
    city=models.CharField(max_length=255)
    zip_code=models.CharField(max_length=255)
    country=models.CharField(max_length=8,default="Bangladesh")
    address=models.CharField(max_length=255)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.full_name +" | "+self.email+" | "+self.mobile+" | "+self.address



class Review(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    star=models.CharField(max_length=1,default="1",choices=(
        ("1","1"),("2","2"),
        ("3","3"),("4","4"),("5","5")))
    description=models.TextField()
    review_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.product.title

    @staticmethod
    def get_all_reviews(product_id):
        return Review.objects.filter(product__id=product_id)

products/forms.py
from .models import Address, Review
from django import forms 


class AddressForm(forms.ModelForm):
    class Meta:
        model=Address
        fields=["full_name","email","mobile","city","zip_code","country","address"]
        

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model=Review
        fields='__all__'
        exclude=["review_by","product"]

products/views.py
from django.shortcuts import render

# Create your views here.

pages/templates/pages/cart.html
{% extends 'base.html' %} {% load static %} {% load custom_filter %} 
{% block title %} Cart {% endblock %} {% block content %} {% csrf_token %}
<style>
  .sub_total__show__box {
    min-width: 350px !important;
    align-items: flex-start !important;
    border: none !important;
    padding: 0 !important;
  }
  .sub__total {
    border: 1px solid var(--cultured);
    padding: 15px 20px;
    border-radius: 3px;
  }
  .procced__to__checkout {
    width: 100%;
    margin-top: 15px !important;
    background-color: var(--black);
    color: white;
    padding: 5px 0px;
    text-align: center;
  }
</style>
<div class="product-minimal" style="justify-content: center">
  <div class="product-showcase">
    <br />
    <h2 class="title">Your Cart</h2>
    {% include 'components/message.html' %}
    <div class="showcase-wrapper has-scrollbar">
      <div class="showcase-container">
        {% if obj_list %} {% for obj in obj_list %}
        <div class="showcase" id="showcase__{{obj.slug}}">
          <a href="#" class="showcase-img-box">
            <img
              src="{{obj.image.url}}"
              alt="relaxed short full sleeve t-shirt"
              width="70"
              class="showcase-img"
            />
          </a>

          <div class="showcase-content">
            <button class="dlt__item remove__item" id="{{obj.slug}}">
              <ion-icon
                name="close-outline"
                role="img"
                class="md hydrated"
                aria-label="close outline"
              ></ion-icon>
            </button>
            <br />
            <a href="{% url 'pages:product-detail' obj.slug %}">
              <h4 class="showcase-title">{{obj.title}}</h4>
            </a>

            <a href="#" class="showcase-category">{{obj.sub_category.name}}</a>
            <div class="quantity__box">
              Quantity :
              <button class="btn minus__btn" id="{{obj.slug}}">-</button>
              <input
                type="text"
                name=""
                disabled
                id="quanityTextBox_{{obj.slug}}"
                value="{{obj.cart_quantity}}"
              />
              <button class="btn increase__btn" id="{{obj.slug}}">+</button>
              <span
                id="spinner__text_{{obj.slug}}"
                style="font-size: 20px; margin-left: 10px"
              ></span>
            </div>
            <div class="price-box" style="margin-top: 5px">
              {% if obj.discount_price %}
              <p class="price">{{obj.discount_price|currency}}</p>
              <del>{{obj.price|currency}}</del>
              <span style="color: var(--green)">
                {{obj.price|show_discount_percentage:obj.discount_price}}
              </span>
              {% else %}
              <p class="price">{{obj.price|currency}}</p>
              {% endif %}
            </div>
          </div>
        </div>
        {% endfor %} {% else %}
        <h3 style="margin-bottom: 10px; font-weight: 200">
          Your cart is empty!!
        </h3>

        {% endif %}
      </div>
    </div>
  </div>

  <!-- sub total show box -->
  <div class="showcase sub_total__show__box">
    <div class="sub__total">
      <h3 style="font-weight: 400; margin-bottom: 5px">
        Sub total
        <span style="font-weight: 200; font-size: 16px">
          Items(<span class="product__count"
            >{{request.session.cart|length}}</span
          >)</span
        >
        :
        <span style="float: right; font-weight: 200" class="sub__total__price"
          >{{total_price|currency}}</span
        >
      </h3>
      <h3 style="font-weight: 200; font-size: 15px; margin-bottom: 5px">
        Delivery Charges :
        <span style="float: right; font-weight: 500">Free</span>
      </h3>
      <br />
      <h3 style="font-weight: 400; margin-bottom: 10px">
        Total :
        <span style="float: right" class="total__price"
          >{{total_price|currency}}</span
        >
      </h3>

      <a href="{% url 'pages:checkout' %}" class="btn procced__to__checkout"
        >Procced to Checkout</a
      >
    </div>
  </div>
  <!-- end sub total show box -->
</div>

{% endblock %} {% block custom_js %}
<script>
  $(document).ready(function () {
    function add_and_dicrese_func(slug, sender, remove = false) {
      var csrf = $("input[name='csrfmiddlewaretoken']").val();

      if (remove == true) {
        if (confirm("Are you sure?")) {
          $("#spinner__text_" + slug + "").html("wait...");
          $(".total__price").html("...");
          $(".sub__total__price").html("...");

          $.ajax({
            url: "{% url 'pages:add-to-cart' %}",
            method: "POST",
            data: { csrfmiddlewaretoken: csrf, slug: slug, sender: "remove" },
            success: function (response) {
              $("#showcase__" + slug + "").fadeOut(100);
              $(".product__count").html(response.item_count);
              $(".total__price").html(response.total_price);
              $(".sub__total__price").html(response.total_price);
            },
          });
        } else {
          return false;
        }
      } else {
        $("#spinner__text_" + slug + "").html("wait...");
        $(".total__price").html("...");
        $(".sub__total__price").html("...");
        $.ajax({
          url: "{% url 'pages:add-to-cart' %}",
          method: "POST",
          data: { csrfmiddlewaretoken: csrf, slug: slug, sender: sender },
          success: function (response) {
            $("#quanityTextBox_" + slug + "").val(response.quantity);
            $("#spinner__text_" + slug + "").html("");
            $(".total__price").html(response.total_price);
            $(".sub__total__price").html(response.total_price);
          },
        });
      }
    }

    $(document).on("click", ".increase__btn", function () {
      var slug = $(this).attr("id");
      add_and_dicrese_func(slug, "increase");
    });

    $(document).on("click", ".minus__btn", function () {
      var slug = $(this).attr("id");
      add_and_dicrese_func(slug, "dicrease");
    });

    $(document).on("click", ".remove__item", function () {
      var slug = $(this).attr("id");
      add_and_dicrese_func(slug, "remove", true);
    });
  });
</script>
{% endblock %}

pages/templates/pages/product-detail.html
{% extends 'base.html' %}
 {% load static %}
  {% load custom_filter %}
 {% block title %} Detail of {{obj.slug}} {% endblock %} 
 {% block content %}
  {% csrf_token %}
<style>
  .small__img {
    width: 70px !important;
    height: 70px !important;
    cursor: pointer;
  }
</style>
<div class="product-featured">
  <h2 class="title" style="display: flex">
    <a href="{% url 'pages:product-list' %}">Products ></a> {{obj.title}}
  </h2>

  <div class="showcase-wrapper has-scrollbar">
    <div class="showcase-container">
      <div class="showcase mb-2">
        <div>
          <div class="showcase-banner">
            <img
              src="{{obj.thumbnail.url}}"
              alt="{{obj.title}}"
              class="showcase-img main__img"
            />
          </div>
          <div style="display: flex; overflow-x: auto" class="has-scrollbar">
            <img src="{{obj.thumbnail.url}}" class="showcase-img small__img" />
            {% for s in obj.product.all %}
            <img src="{{s.image.url}}" class="showcase-img small__img" />

            {% endfor %}
          </div>
        </div>

        <div class="showcase-content">
          <div class="showcase-rating">
            <ion-icon name="star"></ion-icon>
            <ion-icon name="star"></ion-icon>
            <ion-icon name="star"></ion-icon>
            <ion-icon name="star-outline"></ion-icon>
            <ion-icon name="star-outline"></ion-icon>
          </div>

          <a>
            <h3 class="showcase-title">{{obj.title}}</h3>
          </a>

          <p class="showcase-desc">{{obj.description}}</p>

          <div class="price-box">
            {% if obj.discount_price %}
            <p class="price">{{obj.discount_price|currency}}</p>
            <del>{{obj.price|currency}}</del>
            <span style="color: white; background: green; padding: 0px 5px">
              {{obj.price|show_discount_percentage:obj.discount_price}}
            </span>
            {% else %}
            <p class="price">{{obj.price|currency}}</p>
            {% endif %}
          </div>
          <div class="price-box">
            Quantity :
            <input
              type="number"
              name=""
              value="1"
              min="1"
              id="quantity__box"
              style="width: 50px; text-align: center"
            />
          </div>

          <button class="add-cart-btn add__to__cart__btn" id="{{obj.slug}}">
            add to cart
          </button>
          <!--
                    - NOTIFICATION TOAST
                  -->

          <div class="notification__toast" style="display: none">
            <button class="toast__close__btn">
              <ion-icon name="close-outline"></ion-icon>
            </button>
            <div class="toast__detail">
              <p class="toast__title"></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--rating start -->
<div style="display: flex">
  <h3 style="flex: 1" id="reviews">Customer Reviews</h3>
  <a
    href="{% url 'pages:product-review' obj.slug %}"
    class="btn"
    style="border: 1px solid var(--black)"
    >Write a review</a
  >
</div>
<br />
<div class="review__section">
  {% if review_list %} {% for rv in review_list %}
  <div class="review__box">
    <div class="review__header">
      <div class="review__header__left">
        <img
          src="{{rv.review_by.profile_picture.url}}"
          style="width: 45px; height: 45px; border-radius: 5px"
          alt=""
        />
        <p style="margin-left: 10px; font-weight: 300">
          {{rv.review_by.first_name}} {{rv.review_by.last_name}}<br />
          <span style="font-weight: 500; font-size: 15px"
            >{{rv.review_by.username}}</span
          >
        </p>

        <div class="showcase-rating" style="display: flex; color: orange">
          {{rv.star|star_count}}
        </div>
      </div>
    </div>
    <div class="review__description">
      <p>{{rv.description}}</p>
    </div>
  </div>
  <br /><br />
  {% endfor %}
  <div style="display: flex">
    {% if review_list.has_previous %}
    <a href="?page={{review_list.previous_page_number}}#reviews" class="btn">
      Previous
    </a>

    {% endif %}

    <span class="current">
      Page {{ review_list.number }} of {{ review_list.paginator.num_pages }}
    </span>

    {% if review_list.has_next %}
    <a href="?page={{review_list.next_page_number }}#reviews" class="btn">
      Next
    </a>

    {% endif %} {% else %}
    <h3 style="font-weight: 300">Reviews Not found!!!</h3>
    {% endif %}
  </div>
</div>
<!--rating end-->

{% endblock %} {% block custom_js %}

<script>
  $(document).ready(function () {
    $(".add__to__cart__btn").on("click", function () {
      $(".toast__title").html("wait...");
      var slug = $(this).attr("id");
      var quantity = $("#quantity__box").val();
      var csrf = $("input[name='csrfmiddlewaretoken']").val();
      $.ajax({
        url: "{% url 'pages:add-to-cart' %}",
        method: "POST",
        data: {
          csrfmiddlewaretoken: csrf,
          slug: slug,
          quantity: quantity,
          sender: "detail_page",
        },
        success: function (response) {
          $(".toast__title").html(
            "added in your cart & total quantity (" + response.quantity + ")"
          );
          $(".notification__toast").css("display", "block");
          $(".product__count").html(response.item_count);
        },
      });
    });

    $(".toast__close__btn").on("click", function () {
      $(".notification__toast").fadeOut(500);
    });

    $(document).on("click", ".small__img", function () {
      var src = $(this).attr("src");
      $(".main__img").attr({ src: src });
    });
  });
</script>
{% endblock %}

pages/templates/pages/product.html
{% extends 'base.html' %} 
{% load static %}
 {% load custom_filter %}
 {% block title %} All Products {% endblock %} 
 
 {% block content %}
<style>
  [data-pagination],
  [data-pagination] *,
  [data-pagination] *:before,
  [data-pagination] *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-kerning: auto;
  }
  [data-pagination] {
    font-size: 8pt;
    line-height: 1;
    font-weight: 400;
    font-family: "Open Sans", "Source Sans Pro", Roboto, "HelveticaNeue-Light",
      "Helvetica Neue Light", "Helvetica Neue", "Myriad Pro", "Segoe UI", Myriad,
      Helvetica, "Lucida Grande", "DejaVu Sans Condensed", "Liberation Sans",
      "Nimbus Sans L", Tahoma, Geneva, Arial, sans-serif;
    -webkit-text-size-adjust: 100%;
    margin: 1em auto;
    text-align: center;
    transition: font-size 0.2s ease-in-out;
  }
  [data-pagination] ul {
    list-style-type: none;
    display: inline;
    font-size: 100%;
    margin: 0;
    padding: 0.5em;
  }
  [data-pagination] ul li {
    display: inline-block;
    font-size: 100%;
    width: auto;
    border-radius: 3px;
  }
  [data-pagination] > a {
    font-size: 140%;
  }
  [data-pagination] a {
    color: #777;
    font-size: 100%;
    padding: 0.5em;
  }
  [data-pagination] a:focus,
  [data-pagination] a:hover {
    color: #f60;
  }
  [data-pagination] li.current {
    background: rgba(0, 0, 0, 0.1);
  }
  /* Disabled & Hidden Styles */
  [data-pagination] .disabled,
  [data-pagination] [hidden],
  [data-pagination] [disabled] {
    opacity: 0.5;
    pointer-events: none;
  }
  @media (min-width: 350px) {
    [data-pagination] {
      font-size: 10pt;
    }
  }
  @media (min-width: 500px) {
    [data-pagination] {
      font-size: 12pt;
    }
  }
  @media (min-width: 700px) {
    [data-pagination] {
      font-size: 14pt;
    }
  }
  @media (min-width: 900px) {
    [data-pagination] {
      font-size: 16pt;
    }
  }
</style>
{% csrf_token %}
<div class="product-main" id="products">
  <h2 class="title">
    {% if sub_category %} All {{sub_category}}
     {% else %} All Products {% endif%} 
     {% include 'components/message.html' %}
  </h2>

  {% if obj_list %}
  <div class="product-grid">
    {% for obj in obj_list %}
    <div class="showcase">
      <div class="showcase-banner">
        <img
          src="{{obj.image.url}}"
          alt="{{obj.title}}"
          width="300"
          class="product-img default"
        />
       {% if obj.second_image %}
        <img
          src="{{obj.second_image.url}}"
          alt="{{obj.title}}"
          width="300"
          class="product-img hover"
        />
        {% else %}
         <img
          src="{{obj.image.url}}"
          alt="{{obj.title}}"
          width="300"
          class="product-img default"
        />
       {% endif %}

        <div class="showcase-actions">
          <button class="btn-action">
            <ion-icon name="heart-outline"></ion-icon>
          </button>

          <button class="btn-action">
            <ion-icon name="eye-outline"></ion-icon>
          </button>

          <button class="btn-action">
            <ion-icon name="repeat-outline"></ion-icon>
          </button>
        </div>
      </div>

      <div class="showcase-content">
        <a
          href="{% url 'pages:sub_category-list' obj.sub_category.slug %}"
          class="showcase-category"
          >{{obj.sub_category}}</a
        >

        <a href="{% url 'pages:product-detail' obj.slug %}">
          <h3 class="showcase-title">{{obj.title}}</h3>
        </a>

        <div class="price-box" style="float: left">
          {% if obj.discount_price %}
          <p class="price">{{obj.discount_price|currency}}</p>
          <del>{{obj.price|currency}}</del>
          <span style="color: white; background: green; padding: 0px 5px">
            {{obj.price|show_discount_percentage:obj.discount_price}}
          </span>

          {% else %}
          <p class="price">{{obj.price|currency}}</p>
          {% endif %}
        </div>
      </div>

      <button
        class="btn-action add__to__cart__btn add__to__cart__btn__{{obj.slug}}"
        id="{{obj.slug}}"
        {% if obj.is_added_cart %} style="width:100%;color:white;display:flex;background: var(--green);"
        {% else %} style="width: 100%;color: white;display: flex;background: var(--black);"
{%endif%}
      >
        <p style="width: 80%; text-align: left">Add to cart</p>
        <p style="display: flex">
          <ion-icon name="bag-add-outline"></ion-icon>

          <span
            class="single__product__count_{{obj.slug}}"
            style="margin-left: 4px"
          >
            {% if obj.is_added_cart %} ({{obj.cart_quantity}}) {% endif %}
          </span>
        </p>
      </button>
    </div>
    {% endfor %}
  </div>
  <nav data-pagination>
    <a href="#" disabled><i class="ion-chevron-left"></i></a>
    <ul>
      {% if obj_list.has_previous %}
      <li>
        <a href="?page={{obj_list.previous_page_number}}#products">
          <ion-icon
            name="caret-back-outline"
            style="font-size: 40px; margin-bottom: -20px"
          ></ion-icon>
        </a>
      </li>
      {% endif %}
      <li>
        <span class="current">
          Page {{ obj_list.number }} of {{ obj_list.paginator.num_pages }}
        </span>
      </li>

      {% if obj_list.has_next %}
      <li>
        <a href="?page={{obj_list.next_page_number }}#products">
          <ion-icon
            name="caret-forward"
            style="font-size: 40px; margin-bottom: -20px"
          ></ion-icon>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>

  {% else %}
  <h2>Product not Found!!</h2>
  {% endif %}
</div>

{% endblock %} {% block custom_js %}

<script>
  $(document).ready(function () {
    $(".add__to__cart__btn").on("click", function () {
      var slug = $(this).attr("id");
      var quantity = 1;
      var csrf = $("input[name='csrfmiddlewaretoken']").val();
      $(".single__product__count_" + slug + "").html("...");
      $.ajax({
        url: "{% url 'pages:add-to-cart' %}",
        method: "POST",
        data: {
          csrfmiddlewaretoken: csrf,
          slug: slug,
          quantity: quantity,
          sender: "detail_page",
        },
        success: function (response) {
          $(".product__count").html(response.item_count);
          $(".single__product__count_" + slug + "").html(
            "(" + response.quantity + ")"
          );
          $(".add__to__cart__btn__" + slug + "").css(
            "background",
            "var(--green)"
          );
        },
      });
    });
  });
</script>

{% endblock %}

pages/templates/pages/review.html
{% extends 'base.html' %} {% load static %} {% load custom_filter %}
 {% block title %} Review {% endblock %} {% block content %}
<style>

  #id_description{
   outline: 0;
    background: #f2f2f2;
 
    border: 0;
    caret-color: #4f5d7e;
    margin: 10px 0px;
    padding: 10px 10px;
    box-sizing: border-box;
    font-size: 17px;
  }
  .submit__btn{
      padding:5px 7px;
      background:var(--black);
      color:white;
  }
</style>
<div class="product-minimal" style="justify-content: center">
  <div class="product-showcase">
    <br />
    <h2 class="title">Review</h2>
    {% include 'components/message.html' %}
    <div class="showcase-wrapper has-scrollbar">
      <div class="showcase-container">
        <div class="showcase">
          <a href="#" class="showcase-img-box">
            <img
              src="{{obj.thumbnail.url}}"
              alt="relaxed short full sleeve t-shirt"
              width="70"
              class="showcase-img"
            />
          </a>

          <div class="showcase-content">
            <br />
            <a href="{% url 'pages:product-detail' obj.slug %}">
              <h4 class="showcase-title">{{obj.title}}</h4>
            </a>

            <a href="#" class="showcase-category">{{obj.sub_category.name}}</a>
          </div>
        </div>
        <div class="showcase">
          <form action="." method="POST">
            {% csrf_token %}
            <div class="customer__info">
                 {% for field in form %}
                 <div class="form__box">
                    <Label>{{field.name}}: </Label>
                   <span style="float:right"> {{field}}</span>
                </div>
                 {% endfor %}

              </div>
            </div>
            <button class="submit__btn">Submit</button>
              
          </form>
        </div>
      </div>
    </div>
  </div>
 </div>

  {% endblock %}