main_settings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import LoginView, LogoutView, RegisterView


urlpatterns = [
    path('admin/', admin.site.urls),

    path("",include("pages.urls",namespace="pages")), 
    path("login/",LoginView.as_view(),name="login"),
    path("register/",RegisterView.as_view(),name="register"),
    path("logout/",LogoutView.as_view(),name="logout"),
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from .views import*
from accounts.middlewares import customer_middleware
app_name="pages"
urlpatterns = [
       path("",HomeView.as_view(),name='home'),
       path("shop/",ProductListView.as_view(),name='product-list'),
       path("cart/",CartView.as_view(),name='cart'),
       path("checkout/",customer_middleware(CheckoutView.as_view()),name='checkout'),
       path("order/",customer_middleware(OrderView.as_view()),name='order'),
       path("product/detail-of-<slug:slug>/",ProductDetailView.as_view(),name='product-detail'),
       

       path("add-to-cart/",AddToCartView.as_view(),name="add-to-cart"),
       path("category/<slug:slug>/",SubCategoryView.as_view(),name="sub_category-list"),
       path("product/detail-of-<slug:slug>/review/",ProductReviewView.as_view(),name='product-review'),


       path("search-product/<str:query>/",get__names)
      
      

]

products/models.py
import uuid
from django.utils.html import format_html
from django.db import models
from accounts.models import CustomUser
import ast 
from django.utils.text import slugify


# Create your models here.
class BaseModel(models.Model):
    slug=models.SlugField(unique=True,blank=True,null=True)
    updated=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract=True 


class Category(BaseModel):
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(unique=True,blank=True,null=True)

    def __str__(self) -> str:
        return self.name 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args,**kwargs)

class SubCategory(BaseModel):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(blank=True,null=True)

    def __str__(self) -> str:
        return self.name 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args,**kwargs)


class Product(BaseModel):
    sub_category=models.ForeignKey(SubCategory,on_delete=models.CASCADE)
    title=models.CharField(max_length=255,unique=True)
    thumbnail=models.ImageField(upload_to="media")
    price=models.PositiveBigIntegerField()
    discount_price=models.PositiveBigIntegerField(blank=True,null=True)
    description=models.TextField()
    MEN_OR_WOMEN=(("Men's","Men's"),("Women's","Women's"),("Kid's","Kid's"),("Everyone","Everyone"))
    men_or_women=models.CharField(max_length=8,choices=MEN_OR_WOMEN)
    is_active=models.BooleanField(default=True)
    sale_count=models.PositiveBigIntegerField(default=0)

    def __str__(self) -> str:
        return self.title 

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        return super().save(*args,**kwargs)


    def get_all_images(self):
        images=f"<img src='{self.thumbnail.url}' height='25' width='25' style='border-radius:50%;'> - "
        img_list=ProductImage.objects.filter(product__id=self.id)
        for img in img_list:
            images+=f"<img src='{str(img.image.url)}' height='25' width='25' style='border-radius:50%;'> - "
            
        return format_html(images)

    def multiple_image(self):
        img_list=ProductImage.objects.filter(product__id=self.id)
        images=[]
        for obj in img_list:
            images.append(obj.image.url)
        return images



class ProductImage(models.Model):
    product=models.ForeignKey(Product,related_name='product',on_delete=models.CASCADE)
    image=models.ImageField(upload_to="media")

    def __str__(self):
        return self.product.title


def create_random_code():
    code="ES-"+str(uuid.uuid4()).replace("-","").upper()[:10]
    order=Order.objects.filter(unique_id=code)
    while True:
        if order.exists():
            code="ES-"+str(uuid.uuid4()).replace("-","").upper()[:12]
        else:
            break
    return code 

class Order(models.Model):
    unique_id=models.CharField(max_length=12,default=create_random_code,blank=True,null=True)
    name_and_quantity=models.TextField()
    total=models.PositiveBigIntegerField()
    status=models.CharField(max_length=10,choices=(("Pending","Pending"),("Received","Received")),default="Pending")
    paid=models.BooleanField(default=False)
    order_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    updated=models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.unique_id

    def save(self,*args,**kwargs):
        if self.status=="Received":
            self.paid=True 
        return super().save(*args,**kwargs)

    def product_list(self):
        text=ast.literal_eval(self.name_and_quantity)
        data=""
        for i in text:
           obj=Product.objects.get(id=i["id"])
           data+=f"<img src='{obj.thumbnail.url}' style='height:25px;weight:25px;border-radius:50%;'> {Product.objects.get(id=i['id']).title}( {i['quantity']} )<br>"
        return format_html(data)

    
    def customer_details(self):
        address=Address.objects.filter(order__id=self.id).last()
        detail=""
        detail+=f'<p>Name : {address.full_name}</p>'
        detail+=f'<p>Phone : {address.mobile}</p>'
        detail+=f'<p>Email : {address.email}</p>'
        detail+=f'<p>Address : {address.address},{address.city},{address.country}</p>'
        return format_html(detail)




class Address(models.Model):
    full_name=models.CharField(max_length=255)
    email=models.EmailField()
    mobile=models.CharField(max_length=255)
    city=models.CharField(max_length=255)
    zip_code=models.CharField(max_length=255)
    country=models.CharField(max_length=8,default="Bangladesh")
    address=models.CharField(max_length=255)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.full_name +" | "+self.email+" | "+self.mobile+" | "+self.address



class Review(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    star=models.CharField(max_length=1,default="1",choices=(
        ("1","1"),("2","2"),
        ("3","3"),("4","4"),("5","5")))
    description=models.TextField()
    review_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.product.title

    @staticmethod
    def get_all_reviews(product_id):
        return Review.objects.filter(product__id=product_id)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-STORE | {% block title %}{% endblock %}</title>

    <!--
    - favicon
  -->
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/logo/favicon.ico' %}"
      type="image/x-icon"
    />

    <!--
    - custom css link
  -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />

    <!--
    - google font link
  -->
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,900&display=swap"
      rel="stylesheet"
    />

    {% block custom_css %}{% endblock %}

    <style>
      * {
        font-family: "Urbanist", sans-serif;
      }
    </style>
  </head>

  <body>
    <div class="overlay" data-overlay></div>

    <!--
    - HEADER
  -->
    {% include 'header.html' %}
    <!--
    - MAIN
  -->

    <main>
      <!--
      - BANNER
    -->
      {% block banner %}{% endblock %}
      <!--
      - CATEGORY
    -->
      {% block category_section %}{% endblock %}

      <!--
      - PRODUCT
    -->
      <div class="product-container">
        <div class="container">
          <!--
          - SIDEBAR
        -->
          {% include 'components/sidebar.html' %}
          <div class="product-box">
            <br />
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>

      <!--
      - TESTIMONIALS, CTA & SERVICE
    -->
      {% block testimonial_section %}{% endblock %}
      <!--
      - BLOG
    -->
      {% block blog_section %}{% endblock %}
    </main>
    <!--
    - FOOTER
  -->

    {% include 'footer.html' %}

    <!--
    - custom js link
  -->
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>

    <!--
    - ionicon link
  -->
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
    {% block custom_js %}{% endblock %}
    <script>
      $(document).ready(function () {
        $(".message__close__btn").on("click", function () {
          $(".message__toast").fadeOut(500);
        });

        $(document).on("mouseover", ".menu-category", function () {
          $(this)
            .children("a")
            .children("span")
            .html("<ion-icon name='caret-up'></ion-icon>");
        });
        $(document).on("mouseout", ".menu-category", function () {
          $(this)
            .children("a")
            .children("span")
            .html("<ion-icon name='caret-down'></ion-icon>");
        });
      });

         $("#id_description").attr({"rows":5,"placeholder":"Write a review"})
    </script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer>
  <div class="footer-nav">
    <div class="container">
      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Popular Categories</h2>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Fashion</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Electronic</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Cosmetic</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Health</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Watches</a>
        </li>
      </ul>

      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Products</h2>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Prices drop</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">New products</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Best sales</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Contact us</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Sitemap</a>
        </li>
      </ul>

      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Our Company</h2>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Delivery</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Legal Notice</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Terms and conditions</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">About us</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Secure payment</a>
        </li>
      </ul>

      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Services</h2>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Prices drop</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">New products</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Best sales</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Contact us</a>
        </li>

        <li class="footer-nav-item">
          <a href="#" class="footer-nav-link">Sitemap</a>
        </li>
      </ul>

      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Contact</h2>
        </li>

        <li class="footer-nav-item flex">
          <div class="icon-box">
            <ion-icon name="location-outline"></ion-icon>
          </div>

          <address class="content">
            419 State 414 Rte Beaver Dams, New York(NY), 14812, USA
          </address>
        </li>

        <li class="footer-nav-item flex">
          <div class="icon-box">
            <ion-icon name="call-outline"></ion-icon>
          </div>

          <a href="tel:+607936-8058" class="footer-nav-link">(607) 936-8058</a>
        </li>

        <li class="footer-nav-item flex">
          <div class="icon-box">
            <ion-icon name="mail-outline"></ion-icon>
          </div>

          <a href="mailto:example@gmail.com" class="footer-nav-link"
            >example@gmail.com</a
          >
        </li>
      </ul>

      <ul class="footer-nav-list">
        <li class="footer-nav-item">
          <h2 class="nav-title">Follow Us</h2>
        </li>

        <li>
          <ul class="social-link">
            <li class="footer-nav-item">
              <a href="#" class="footer-nav-link">
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li class="footer-nav-item">
              <a href="#" class="footer-nav-link">
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li class="footer-nav-item">
              <a href="#" class="footer-nav-link">
                <ion-icon name="logo-linkedin"></ion-icon>
              </a>
            </li>

            <li class="footer-nav-item">
              <a href="#" class="footer-nav-link">
                <ion-icon name="logo-instagram"></ion-icon>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="container">
      <img
        src="{% static 'assets/images/payment.png'%}"
        alt="payment method"
        class="payment-img"
      />

      <p class="copyright">
        Copyright &copy; <a href="#">Anon</a> all rights reserved.
      </p>
    </div>
  </div>
</footer>

templates/header.html
{% load static %}

<header>
  
  <div class="header-main">
    <div class="container">
      <a
        href="{% url 'pages:home' %}"
        class="header-logo"
        style="display: flex; align-items: center"
      >
        <h2 style="color: white">E-STORE</h2>
      </a>

      

        <div class="header-search-container">
          <form action="{% url 'pages:product-list' %}" method="get">
        <input
          type="search"
          name="qry"
          class="search-field"
          placeholder="search here..."
          required
        />

        <button class="search-btn">
          <ion-icon name="search-outline"></ion-icon>
        </button>
        </form>
      </div>
      

      <div class="header-user-actions">
        {% if request.user.is_authenticated %}
        <ul class="desktop-menu-category-list">
          <li class="menu-category">
            <a
              class="menu-title customer__dropdown"
              style="display: flex; color: white; align-items: center"
            >
              {% if request.user.username %}
               {{request.user.username}}
                {% else%}
                 {{request.user.email}}
                  {% endif %}
              <img
                src="{{request.user.profile_picture.url}}"
                style="width: 30px; height: 30px"
                alt=""
              />
            </a>
            <ul
              class="dropdown-list"
              style="padding: 5px 3px; width: 160px; color: white"
            >
              <li class="dropdown-item">
                <a href="{% url 'pages:order' %}" style="color: black"
                  >My Orders</a
                >
              </li>

              <li
                class="dropdown-item"
                style="background-color: black; margin-top: 5px"
              >
                <a href="{% url 'logout' %}" style="color: white">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
        {% else %}
        <a
          href="{% url 'login' %}"
          style="color: white; background: var(--black); padding: 5px 10px"
          >Login</a
        >
        {% endif %}

        <button class="action-btn">
          <a href="{% url 'pages:cart' %}" style="color: white">
            <ion-icon name="cart-outline"></ion-icon>
            <span class="count product__count"
              >{{request.session.cart|length}}</span
            >
          </a>
        </button>
      </div>
    </div>
  </div>



  <nav class="desktop-navigation-menu">
    <div class="container">
      <ul class="desktop-menu-category-list">
        <li class="menu-category">
          <a href="{% url 'pages:home' %}" class="menu-title">Home</a>
        </li>

        <li class="menu-category">
          <a href="{% url 'pages:product-list' %}" class="menu-title">Shop</a>
        </li>
        {% if men_sub_category %}
        <li class="menu-category">
          <a href="#" class="menu-title" style="display: flex"
            >Men's
            <span>
              <ion-icon name="caret-down"></ion-icon>
            </span>
          </a>

          <ul class="dropdown-list">
            {% for obj in men_sub_category %}
            <li class="dropdown-item">
              <a href="{% url 'pages:sub_category-list' obj.slug %}"
                >{{obj.name}}</a
              >
            </li>
            {% endfor %}
          </ul>
        </li>
        {% endif %} {% if women_sub_category %}
        <li class="menu-category">
          <a href="#" class="menu-title" style="display: flex"
            >Women's
            <span>
              <ion-icon name="caret-down"></ion-icon>
            </span>
          </a>

          <ul class="dropdown-list">
            {% for obj in women_sub_category %}
            <li class="dropdown-item">
              <a href="{% url 'pages:sub_category-list' obj.slug %}"
                >{{obj.name}}</a
              >
            </li>
            {% endfor %}
          </ul>
        </li>
        {% endif %} {% if kid_sub_category %}
        <li class="menu-category">
          <a href="#" class="menu-title" style="display: flex"
            >Kid's & Babies
            <span>
              <ion-icon name="caret-down"></ion-icon>
            </span>
          </a>
          <ul class="dropdown-list">
            {% for obj in kid_sub_category %}
            <li class="dropdown-item">
              <a href="{% url 'pages:sub_category-list' obj.slug %}"
                >{{obj.name}}</a
              >
            </li>
            {% endfor %}
          </ul>
        </li>
        {% endif %}

        <li class="menu-category">
          <a href="#" class="menu-title">Blog</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="mobile-bottom-navigation">
    <button class="action-btn" data-mobile-menu-open-btn>
      <ion-icon name="menu-outline"></ion-icon>
    </button>

    <a href="{% url 'pages:cart' %}" class="action-btn">
      <ion-icon name="notifications-outline"></ion-icon>
      <span class="count" style="background-color: tomato">0</span>
    </a>
    <a href="{% url 'pages:home' %}" class="action-btn">
      <ion-icon name="home-outline"></ion-icon>
    </a>
    <a href="{% url 'pages:cart' %}" class="action-btn">
      <ion-icon name="cart-outline"></ion-icon>
      <span class="count product__count">{{request.session.cart|length}}</span>
    </a>

    <a href="#" class="action-btn">
      <ion-icon name="person-circle-outline"></ion-icon>
    </a>
  </div>

  <nav class="mobile-navigation-menu has-scrollbar" data-mobile-menu>
    <div class="menu-top">
      <h2 class="menu-title">Menu</h2>

      <button class="menu-close-btn" data-mobile-menu-close-btn>
        <ion-icon name="close-outline"></ion-icon>
      </button>
    </div>

    <ul class="mobile-menu-category-list">
      <li class="menu-category">
        <a href="{% url 'pages:home' %}" class="menu-title">Home</a>
      </li>
      <li class="menu-category">
        <a href="{% url 'pages:product-list' %}" class="menu-title">Shop</a>
      </li>
      {% for c in sub_category_list %}
      <li class="menu-category">
        <button class="accordion-menu" data-accordion-btn>
          <p class="menu-title">{{c.name}}</p>

          <div>
            <ion-icon name="add-outline" class="add-icon"></ion-icon>
            <ion-icon name="remove-outline" class="remove-icon"></ion-icon>
          </div>
        </button>

        <ul class="submenu-category-list" data-accordion>
          {% for s in c.subcategory_set.all %}
          <li class="submenu-category">
            <a
              href="{% url 'pages:sub_category-list' s.slug %}"
              class="submenu-title"
              >{{s.name}}</a
            >
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}

      <li class="menu-category">
        <a href="#" class="menu-title">Blog</a>
      </li>

      <li class="menu-category">
        <a href="#" class="menu-title">Hot Offers</a>
      </li>
    </ul>

    <div class="menu-bottom">
      <ul class="menu-category-list">
        <li class="menu-category">
          <button class="accordion-menu" data-accordion-btn>
            <p class="menu-title">Language</p>

            <ion-icon name="caret-back-outline" class="caret-back"></ion-icon>
          </button>

          <ul class="submenu-category-list" data-accordion>
            <li class="submenu-category">
              <a href="#" class="submenu-title">English</a>
            </li>

            <li class="submenu-category">
              <a href="#" class="submenu-title">Bangla</a>
            </li>
          </ul>
        </li>

        <li class="menu-category">
          <button class="accordion-menu" data-accordion-btn>
            <p class="menu-title">Currency</p>
            <ion-icon name="caret-back-outline" class="caret-back"></ion-icon>
          </button>

          <ul class="submenu-category-list" data-accordion>
            <li class="submenu-category">
              <a href="#" class="submenu-title">BDT ৳</a>
            </li>

            <li class="submenu-category">
              <a href="#" class="submenu-title">USD &dollar;</a>
            </li>
          </ul>
        </li>
      </ul>

      <ul class="menu-social-container">
        <li>
          <a href="#" class="social-link">
            <ion-icon name="logo-facebook"></ion-icon>
          </a>
        </li>

        <li>
          <a href="#" class="social-link">
            <ion-icon name="logo-twitter"></ion-icon>
          </a>
        </li>

        <li>
          <a href="#" class="social-link">
            <ion-icon name="logo-instagram"></ion-icon>
          </a>
        </li>

        <li>
          <a href="#" class="social-link">
            <ion-icon name="logo-linkedin"></ion-icon>
          </a>
        </li>
      </ul>
    </div>
    {% csrf_token %}
  </nav>
</header>